# Site settings
# Variables are accessible in the templates via {{ site.myvariable }}.

title: Panodio
subtitle: An audio interface to the acoustic web
description: >- 
  And maybe an agent to all of the audio resources on the Web
baseurl: ""
url: https://panodio.panoptikum.social
email: stefan@panoptikum.social
twitter_username: panodio
github_username:  haslinger

language: en
keywords: [audio, podcast, interface, android]
license: AGPL3

author: Stefan Haslinger
author_url: "https://panoptikum.social/informatom"
date_format: ordinal

plugins:
  - jekyll-feed
  - jekyll-postcss-v2

exclude:
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
