title: Panodio
email: stefan@panodio.io
description: >- 
  Here needs to go a short description
baseurl: "/" 
url: "https://panod.io" 
twitter_username: panodio
github_username:  haslinger

markdown: kramdown
theme: jekyll-bootflat
plugins:
  - jekyll-feed

