title: Panodio.Panoptikum.social
url: https://panodio.panoptikum.social
download_url: "https://panodio.panoptikum.social/episodes"
subtitle: An audio interface to the acoustic web
description: And maybe an agent to all of the audio resources on the Web
author: Stefan Haslinger
author_url: "https://panoptikum.social/informatom"
email: stefan@panoptikum.social
keywords: [audio, podcast, interface, android]
itunes_categories: [Technology]
episodes_per_feed_page: 100
date_format: "ordinal"
rsync_delete: true
twitter_nick: panodio
language: en
explicit: "no" # 'yes'/'no'/clean
license: AGPL3
itunes_url: "https://itunes.apple.com/at/podcast/myname/id#myid#"
## Isso comments #########################################################
use_isso: no # set to 'yes' to include isso comments form

plugins: [jekyll-octopod]
theme: jekyll-bootflat
